### ISSUE TITLE
An issue in matlab code

### ISSUE THREAD

**Issue by EasonHuang-tw** [fdcl-gwu/se3_geometric_control#13]
Hi,
in file matlab/position_control.m line 105
I think it suppose to be "+ hat(b2c) * b3c_ddot;"
not + hat(b2c) * b2c_ddot;

thanks

**Comment by kanishkegb** [comment]
Thank you for pointing this out, and this is definitely a typo. This has been fixed in [f7cc2d1](https://github.com/fdcl-gwu/uav_geometric_control/commit/f7cc2d1c772016666d025f75ced7cf4f7634a59b).
